/**
 * Shared data types for Frame Lab.
 *
 * Character JSON files in `src/data/characters/` are generated by
 * `scripts/import-fightcore.mjs` and must match the `CharacterData` shape.
 * Distances are in Melee's in-game units; frames are 60ths of a second.
 */

/** One entry in the fixed 26-character roster (see roster.json). */
export interface RosterEntry {
  /** URL-safe id, also used for icon and clip file names, e.g. "captain-falcon". */
  id: string;
  name: string;
  /** Short label for small roster tiles, e.g. "Falcon". */
  shortName: string;
  /** Character key in FightCore's data set. */
  fightCoreName: string;
  /** Character key in libmelee's characterdata.csv. */
  libmeleeName: string;
}

export type MoveCategory = 'ground' | 'aerial' | 'special' | 'grab';

export interface Hitbox {
  name: string;
  damage: number;
  /** Launch angle in degrees. 361 is the Sakurai angle. */
  angle: number;
  baseKnockback: number;
  knockbackGrowth: number;
  /** Non-zero means the hitbox uses set knockback instead of scaling with percent. */
  setKnockback: number;
  isWeightIndependent: boolean;
  /** For example "Normal", "Electric", or "Fire". */
  effect: string;
  shieldstun: number;
  hitlag: number;
}

/** A window of frames in which a group of hitboxes is active. */
export interface Hit {
  /** Source label such as "clean" or "late", when the data has one. */
  name: string | null;
  /** Null when the source data does not say which frames this hit covers. */
  startFrame: number | null;
  endFrame: number | null;
  hitboxes: Hitbox[];
}

export interface Move {
  /** Stable id from the source data, e.g. "usmash". Also used for clip file names. */
  id: string;
  name: string;
  category: MoveCategory;
  totalFrames: number | null;
  /** First frame any hitbox is active. */
  firstActiveFrame: number | null;
  lastActiveFrame: number | null;
  /** First frame the move can be interrupted by another action. */
  iasa: number | null;
  landingLag: number | null;
  lCancelledLandingLag: number | null;
  autoCancelBefore: number | null;
  autoCancelAfter: number | null;
  notes: string | null;
  hits: Hit[];
}

export interface CharacterAttributes {
  weight: number;
  /** Downward acceleration per frame while airborne. */
  gravity: number;
  /** Maximum normal falling speed (terminal velocity). */
  fallSpeed: number;
  fastFallSpeed: number;
}

export interface CharacterData {
  id: string;
  name: string;
  attributes: CharacterAttributes;
  /** Moves in display order, already grouped by category. */
  moves: Move[];
  /** Where this character's data came from. */
  sources: string[];
}

export interface Platform {
  /** Height of the platform's top surface. */
  y: number;
  left: number;
  right: number;
  /** True if the platform moves during a match (Fountain of Dreams). */
  isMoving?: boolean;
}

export interface Stage {
  id: string;
  name: string;
  shortName: string;
  blastZones: { left: number; right: number; top: number; bottom: number };
  /** X position of the right edge of the main stage. The left edge is the same value, negated. */
  edgeX: number;
  platforms: Platform[];
}
